name: 'S3 Upload Action'
description: 'This is a GitHub Action to upload files to Amazon S3.'
author: 'Hiroyuki Kusu'
inputs:
  s3-bucket:
    description: ''
    required: true
  source-path:
    description: ''
    required: true
  destination-path:
    description: ''
    required: true
  download-base-url:
    description: ''
    required: false
  download-qr-path:
    description: ''
    required: false
  download-qr-width:
    description: ''
    default: 100
    required: false
outputs:
  download-url:
    description: ''
  download-qr-url:
    description: ''
  result:
    description: '`success` or `failure` is set.'
runs:
  using: 'node12'
  main: 'dist/index.js'
