name: 'S3 Upload Action'
description: 'This is a GitHub Action that uploads a file to Amazon S3.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  aws-access-key-id:
    description: ''
    required: true
  aws-secret-access-key:
    description: ''
    required: true
  aws-region:
    description: ''
    required: true
  aws-bucket:
    description: ''
    required: true
  file-path:
    description: ''
    required: true
  content-type:
    description: ''
    required: false
  destination-dir:
    description: ''
    required: false
  private:
    description: ''
    default: 'true'
    required: false
  output-url:
    description: ''
    default: 'false'
    required: false
  expire:
    description: ''
    default: '86400'
    required: false
  create-qr:
    description: ''
    default: 'false'
    required: false
  qr-width:
    description: ''
    default: '120'
    required: false
  bucket-root:
    description: ''
    default: 'artifacts'
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
  file-url:
    description: ''
  qr-url:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
