name: S3 Upload

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  post:
    name: Use this action for check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Use this action
        uses: ./
        id: upload
        with:
          s3-bucket: ${{ secrets.S3_BUCKET}}
          download-base-url: 'http:/${{ secrets.S3_BUCKET}}.s3-website-ap-northeast-1.amazonaws.com'
          download-dir: 'abcdefg'
          path: sample.txt
          upload-qr-code-image: true
      - name: Show result
        if: always()
        run: |
          echo '${{ steps.upload.outputs.download-url }}'
          echo '${{ steps.upload.outputs.download-qr-url }}'
          echo '${{ steps.upload.outputs.result }}'
